spring.application.name=file-manager

server.port=${FILE_MANAGER_PORT}
media.backup.path=${BACKUP_PATH}

kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVER:localhost:9092}

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD}

minio.container.url=${MINIO_CONTAINER_URL:http://minio:9000}
minio.url=${MINIO_URL:http://localhost:9000}
minio.access-key=${MINIO_ACCESS_KEY}
minio.secret-key=${MINIO_SECRET_KEY}

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.database=media_catalog
spring.data.mongodb.username=admin
spring.data.mongodb.password=strongpassword
spring.data.mongodb.authentication-database=admin
spring.data.mongodb.replica-set-name=rs0