spring.application.name=file-manager

server.port=${FILE_MANAGER_PORT}

auth-server=${AUTH_SERVER:http://localhost:8084}

kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVER}

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD}

minio.container.url=${MINIO_CONTAINER_URL:http://minio:9000}
minio.url=${MINIO_URL:http://localhost:9000}
minio.access-key=${MINIO_ACCESS_KEY}
minio.secret-key=${MINIO_SECRET_KEY}

spring.data.mongodb.host=${MONGODB_HOST:localhost}
spring.data.mongodb.port=${MONGODB_PORT:27017}
spring.data.mongodb.database=${MONGODB_DATABASE:media_catalog}
spring.data.mongodb.username=${MONGODB_USERNAME:admin}
spring.data.mongodb.password=${MONGODB_PASSWORD:strongpassword}
spring.data.mongodb.auto-index-creation=${MONGODB_AUTO_INDEX:true}
spring.data.mongodb.authentication-database=${MONGODB_AUTH_SOURCE:admin}
spring.data.mongodb.replica-set-name=rs0