###
POST http://localhost/api/search?
    searchString=Nier Automata&
    page=0&
    sortByYear=false&
    sortOrder=DESC

###
POST http://localhost/api/search/keyword?
    page=0&
    sortByYear=false&
    sortOrder=DESC
Content-Type: application/json

{
  "field": "universes",
  "text": ["Nier Automata"]
}

###
POST http://localhost/api/search/match?
    page=0&
    sortByYear=false&
    sortOrder=DESC
Content-Type: application/json

{
  "field": "universes",
  "text": ["Nier Automata"]
}

###
GET http://localhost/api/videos/preview/1

###
GET http://localhost/api/videos/partial/1/p360