CREATE TABLE IF NOT EXISTS auth.users
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email     VARCHAR(255) NOT NULL
        CONSTRAINT uq_users_email UNIQUE,
    password  VARCHAR(255) NOT NULL,
    role      SMALLINT NOT NULL
        CONSTRAINT chk_users_role CHECK (role >= 0 AND role <= 1),
    username  VARCHAR(255) NOT NULL
        CONSTRAINT uq_users_username UNIQUE
);
