-- MEDIA METADATA ROOT TABLE
CREATE TABLE IF NOT EXISTS media.media_metadata
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bucket             VARCHAR(255) NOT NULL,
    height             INTEGER      NOT NULL,
    key                TEXT,
    length             INTEGER      NOT NULL,
    parent_path        TEXT         NOT NULL,
    size               BIGINT       NOT NULL,
    thumbnail          TEXT,
    preview            TEXT,
    title              TEXT         NOT NULL,
    upload_date        TIMESTAMPTZ  NOT NULL,
    width              INTEGER      NOT NULL,
    year               SMALLINT     NOT NULL,
    absolute_file_path TEXT         NOT NULL,
    format             VARCHAR(255) NOT NULL,
    frame_rate         SMALLINT     NOT NULL
);

-- MEDIA GROUPS (SELF + MEDIA REFERENCES)
CREATE TABLE IF NOT EXISTS media.media_groups
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grouper_id BIGINT,
    media_id   BIGINT,
    num_info   INTEGER NOT NULL,

    CONSTRAINT fk_media_groups_self
        FOREIGN KEY (grouper_id)
            REFERENCES media.media_groups(id),

    CONSTRAINT fk_media_groups_media
        FOREIGN KEY (media_id)
            REFERENCES media.media_metadata(id)
);

CREATE INDEX IF NOT EXISTS idx_media_groups_media_id
    ON media.media_groups (media_id);

-- AUTHORS
CREATE TABLE IF NOT EXISTS media.authors
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    length INTEGER      NOT NULL,
    name   VARCHAR(255) NOT NULL
        CONSTRAINT uq_authors_name UNIQUE
);

-- CHARACTERS
CREATE TABLE IF NOT EXISTS media.characters
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    length    INTEGER      NOT NULL,
    name      VARCHAR(255) NOT NULL
        CONSTRAINT uq_characters_name UNIQUE,
    thumbnail VARCHAR(255)
);

-- UNIVERSES
CREATE TABLE IF NOT EXISTS media.universes
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    length    INTEGER      NOT NULL,
    name      VARCHAR(255) NOT NULL
        CONSTRAINT uq_universes_name UNIQUE,
    thumbnail VARCHAR(255)
);

-- TAGS
CREATE TABLE IF NOT EXISTS media.tags
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    length INTEGER      NOT NULL,
    name   VARCHAR(255) NOT NULL
        CONSTRAINT uq_tags_name UNIQUE
);

-- M:N RELATION TABLES
CREATE TABLE IF NOT EXISTS media.authors_media
(
    media_id   BIGINT NOT NULL,
    authors_id BIGINT NOT NULL,

    CONSTRAINT fk_authors_media_media
        FOREIGN KEY (media_id)
            REFERENCES media.media_metadata(id),

    CONSTRAINT fk_authors_media_author
        FOREIGN KEY (authors_id)
            REFERENCES media.authors(id),

    PRIMARY KEY (media_id, authors_id)
);

CREATE TABLE IF NOT EXISTS media.characters_media
(
    media_id      BIGINT NOT NULL,
    characters_id BIGINT NOT NULL,

    CONSTRAINT fk_characters_media_media
        FOREIGN KEY (media_id)
            REFERENCES media.media_metadata(id),

    CONSTRAINT fk_characters_media_character
        FOREIGN KEY (characters_id)
            REFERENCES media.characters(id),

    PRIMARY KEY (media_id, characters_id)
);

CREATE TABLE IF NOT EXISTS media.universes_media
(
    media_id     BIGINT NOT NULL,
    universes_id BIGINT NOT NULL,

    CONSTRAINT fk_universes_media_media
        FOREIGN KEY (media_id)
            REFERENCES media.media_metadata(id),

    CONSTRAINT fk_universes_media_universe
        FOREIGN KEY (universes_id)
            REFERENCES media.universes(id),

    PRIMARY KEY (media_id, universes_id)
);

CREATE TABLE IF NOT EXISTS media.tags_media
(
    media_id BIGINT NOT NULL,
    tags_id  BIGINT NOT NULL,

    CONSTRAINT fk_tags_media_media
        FOREIGN KEY (media_id)
            REFERENCES media.media_metadata(id),

    CONSTRAINT fk_tags_media_tag
        FOREIGN KEY (tags_id)
            REFERENCES media.tags(id),

    PRIMARY KEY (media_id, tags_id)
);
