CREATE TABLE IF NOT EXISTS auth.users
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email     VARCHAR(255) NOT NULL
        CONSTRAINT uq_users_email UNIQUE,
    password  VARCHAR(255) NOT NULL,
    role      SMALLINT NOT NULL
        CONSTRAINT chk_users_role CHECK (role >= 0 AND role <= 1),
    username  VARCHAR(255) NOT NULL
        CONSTRAINT uq_users_username UNIQUE
);

DO $$
    BEGIN
        -- 1. ID Column
        ALTER TABLE auth.users ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY;
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'users_pkey') THEN
            ALTER TABLE auth.users ADD PRIMARY KEY (id);
        END IF;

        -- 2. Email Column + Named Unique Constraint
        ALTER TABLE auth.users ADD COLUMN IF NOT EXISTS email VARCHAR(255) NOT NULL DEFAULT 'temporary_user';
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uq_users_email') THEN
            ALTER TABLE auth.users ADD CONSTRAINT uq_users_email UNIQUE (email);
        END IF;

        -- 3. Password Column
        ALTER TABLE auth.users ADD COLUMN IF NOT EXISTS password VARCHAR(255) NOT NULL DEFAULT 'temporary_user';

        -- 4. Role Column + Named Check Constraint
        ALTER TABLE auth.users ADD COLUMN IF NOT EXISTS role SMALLINT NOT NULL DEFAULT 0;
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_users_role') THEN
            ALTER TABLE auth.users ADD CONSTRAINT chk_users_role CHECK (role >= 0 AND role <= 1);
        END IF;

        -- 5. Username Column + Named Unique Constraint
        ALTER TABLE auth.users ADD COLUMN IF NOT EXISTS username VARCHAR(255) NOT NULL DEFAULT 'temporary_user';
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uq_users_username') THEN
            ALTER TABLE auth.users ADD CONSTRAINT uq_users_username UNIQUE (username);
        END IF;

    END $$;