spring.application.name=workers

server.port=${WORKERS_PORT}

auth-server=${AUTH_SERVER:http://localhost:8084}

kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVER}

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD}

minio.container.url=${MINIO_CONTAINER_URL:http://minio:9000}
minio.url=${MINIO_URL:http://localhost:9000}
minio.access-key=${MINIO_ACCESS_KEY}
minio.secret-key=${MINIO_SECRET_KEY}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.jpa.hibernate.ddl-auto=none

spring.datasource.username=media_handler
spring.datasource.password=${DB_MEDIA_HANDLER_PASSWORD}
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432}/media_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=${DB_POOL_SIZE:10}
spring.datasource.hikari.minimum-idle=${DB_MIN_IDLE:2}
spring.datasource.hikari.pool-name=${DB_POOL_NAME:media-db-pool}
spring.datasource.hikari.connection-init-sql=SET search_path TO media

ffmpeg-name=${FFMPEG_NAME:}

allowed-origins=${WEBSOCKET_ALLOWED_ORIGINS:http://localhost:8080}

spring.threads.virtual.enabled=true