worker_processes auto;

events {
    worker_connections 1024;
}

http {
    # Essential for serving static files correctly
    include       mime.types;
    default_type  application/octet-stream;

    # Use Docker’s internal DNS server (127.0.0.11) for name lookups
    resolver 127.0.0.11 ipv6=off valid=30s;

    # Lua Configuration
    lua_package_path "/usr/local/openresty/nginx/lua/?.lua;;";
    lua_shared_dict jwks_cache 1m;

    # =====================================
    # Rate Limiting Zones (Memory Allocations)
    # =====================================
    limit_req_zone $binary_remote_addr zone=login_zone:10m rate=5r/m;
    limit_req_zone $binary_remote_addr zone=api_zone:20m rate=50r/m;
    limit_req_zone $binary_remote_addr zone=static_zone:30m rate=10r/s;
    limit_req_zone $binary_remote_addr zone=stream_zone:50m rate=150r/s;
    limit_req_zone $binary_remote_addr zone=upload_zone:10m rate=5r/m;
    limit_req_zone $binary_remote_addr zone=file_zone:10m rate=15r/m;

    # =====================================
    # Upstreams
    # =====================================
    upstream minio {
        server minio:9000;
    }

    # Pull in the routing files
    include /usr/local/openresty/nginx/conf/conf.d/*.conf;
}