-- USERS
CREATE TABLE IF NOT EXISTS auth.users
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email     VARCHAR(255) NOT NULL
    CONSTRAINT uq_users_email UNIQUE,
    password  VARCHAR(255) NOT NULL,
    role      SMALLINT NOT NULL
    CONSTRAINT chk_users_role CHECK (role >= 0 AND role <= 1),
    username  VARCHAR(255) NOT NULL
    CONSTRAINT uq_users_username UNIQUE
);

DO $$
BEGIN
        -- 1. ID Column
ALTER TABLE auth.users ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY;
IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'users_pkey') THEN
ALTER TABLE auth.users ADD PRIMARY KEY (id);
END IF;

        -- 2. Email Column + Named Unique Constraint
ALTER TABLE auth.users ADD COLUMN IF NOT EXISTS email VARCHAR(255) NOT NULL DEFAULT 'temporary_user';
IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uq_users_email') THEN
ALTER TABLE auth.users ADD CONSTRAINT uq_users_email UNIQUE (email);
END IF;

        -- 3. Password Column
ALTER TABLE auth.users ADD COLUMN IF NOT EXISTS password VARCHAR(255) NOT NULL DEFAULT 'temporary_user';

-- 4. Role Column + Named Check Constraint
ALTER TABLE auth.users ADD COLUMN IF NOT EXISTS role SMALLINT NOT NULL DEFAULT 0;
IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_users_role') THEN
ALTER TABLE auth.users ADD CONSTRAINT chk_users_role CHECK (role >= 0 AND role <= 1);
END IF;

        -- 5. Username Column + Named Unique Constraint
ALTER TABLE auth.users ADD COLUMN IF NOT EXISTS username VARCHAR(255) NOT NULL DEFAULT 'temporary_user';
IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uq_users_username') THEN
ALTER TABLE auth.users ADD CONSTRAINT uq_users_username UNIQUE (username);
END IF;

END $$;


-- MEDIA METADATA ROOT TABLE
CREATE TABLE IF NOT EXISTS media.media_metadata
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    user_id            BIGINT NOT NULL,
    bucket             VARCHAR(255),
    key                TEXT,
    title              TEXT         NOT NULL,
    thumbnail          TEXT,
    preview            TEXT,
    media_type         VARCHAR(32)  NOT NULL,
    length             INTEGER      NOT NULL,
    size               BIGINT       NOT NULL,
    upload_date        TIMESTAMPTZ  NOT NULL,
    width              INTEGER      NOT NULL,
    height             INTEGER      NOT NULL,
    year               SMALLINT     NOT NULL,
    format             VARCHAR(255) NOT NULL,
    frame_rate         SMALLINT     NOT NULL,
    PRIMARY KEY (user_id, id),
    CONSTRAINT fk_media_metadata_users
        FOREIGN KEY (user_id)
            REFERENCES auth.users(id)
);

-- MEDIA GROUPS (SELF + MEDIA REFERENCES)
CREATE TABLE IF NOT EXISTS media.media_groups
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grouper_id BIGINT,
    media_id   BIGINT,
    num_info   TEXT,

    CONSTRAINT fk_media_groups_self
        FOREIGN KEY (grouper_id)
            REFERENCES media.media_groups(id),

    CONSTRAINT fk_media_groups_media
        FOREIGN KEY (media_id)
            REFERENCES media.media_metadata(id)
);

CREATE INDEX idx_media_groups_grouper_id_num_info
    ON media.media_groups (grouper_id, num_info);

-- AUTHORS
CREATE TABLE IF NOT EXISTS media.authors
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    user_id BIGINT       NOT NULL,
    length  INTEGER      NOT NULL,
    name    VARCHAR(255) NOT NULL,
    PRIMARY KEY (user_id, id),
    CONSTRAINT uq_authors_user_name UNIQUE (user_id, name),
    CONSTRAINT fk_authors_users
        FOREIGN KEY (user_id)
            REFERENCES auth.users(id)
);

-- CHARACTERS
CREATE TABLE IF NOT EXISTS media.characters
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    user_id   BIGINT       NOT NULL,
    length    INTEGER      NOT NULL,
    name      VARCHAR(255) NOT NULL,
    thumbnail VARCHAR(255),
    PRIMARY KEY (user_id, id),
    CONSTRAINT uq_characters_user_name UNIQUE (user_id, name),
    CONSTRAINT fk_characters_users
        FOREIGN KEY (user_id)
            REFERENCES auth.users(id)
);

-- UNIVERSES
CREATE TABLE IF NOT EXISTS media.universes
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    user_id   BIGINT       NOT NULL,
    length    INTEGER      NOT NULL,
    name      VARCHAR(255) NOT NULL,
    thumbnail VARCHAR(255),
    PRIMARY KEY (user_id, id),
    CONSTRAINT uq_universes_user_name UNIQUE (user_id, name),
    CONSTRAINT fk_universes_users
        FOREIGN KEY (user_id)
            REFERENCES auth.users(id)
);

-- TAGS
CREATE TABLE IF NOT EXISTS media.tags
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    user_id   BIGINT       NOT NULL,
    length    INTEGER      NOT NULL,
    name      VARCHAR(255) NOT NULL,
    PRIMARY KEY (user_id, id),
    CONSTRAINT uq_tags_user_name UNIQUE (user_id, name),
    CONSTRAINT fk_tags_users
        FOREIGN KEY (user_id)
            REFERENCES auth.users(id)
);

-- M:N RELATION TABLES
CREATE TABLE IF NOT EXISTS media.authors_media
(
    media_id   BIGINT NOT NULL,
    authors_id BIGINT NOT NULL,

    CONSTRAINT fk_authors_media_media
        FOREIGN KEY (media_id)
            REFERENCES media.media_metadata(id),

    CONSTRAINT fk_authors_media_author
        FOREIGN KEY (authors_id)
            REFERENCES media.authors(id),

    PRIMARY KEY (media_id, authors_id)
);

CREATE TABLE IF NOT EXISTS media.characters_media
(
    media_id      BIGINT NOT NULL,
    characters_id BIGINT NOT NULL,

    CONSTRAINT fk_characters_media_media
        FOREIGN KEY (media_id)
            REFERENCES media.media_metadata(id),

    CONSTRAINT fk_characters_media_character
        FOREIGN KEY (characters_id)
            REFERENCES media.characters(id),

    PRIMARY KEY (media_id, characters_id)
);

CREATE TABLE IF NOT EXISTS media.universes_media
(
    media_id     BIGINT NOT NULL,
    universes_id BIGINT NOT NULL,

    CONSTRAINT fk_universes_media_media
        FOREIGN KEY (media_id)
            REFERENCES media.media_metadata(id),

    CONSTRAINT fk_universes_media_universe
        FOREIGN KEY (universes_id)
            REFERENCES media.universes(id),

    PRIMARY KEY (media_id, universes_id)
);

CREATE TABLE IF NOT EXISTS media.tags_media
(
    media_id BIGINT NOT NULL,
    tags_id  BIGINT NOT NULL,

    CONSTRAINT fk_tags_media_media
        FOREIGN KEY (media_id)
            REFERENCES media.media_metadata(id),

    CONSTRAINT fk_tags_media_tag
        FOREIGN KEY (tags_id)
            REFERENCES media.tags(id),

    PRIMARY KEY (media_id, tags_id)
);
