###
# @no-log
POST http://localhost:8084/auth/login
Content-Type: application/json

{
  "username": "test@email.com",
  "password": "SomePass123!"
}


###
# @no-log
GET http://localhost/test-auth






