services:
  auth-service:
    build:
      context: ../auth-service
      dockerfile: Dockerfile
      args:
        SERVICE_PORT: ${AUTH_SERVICE_PORT}
    ports:
      - "${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - AUTH_SERVICE_PORT=${AUTH_SERVICE_PORT}

      - TEST_USER_USERNAME=${TEST_USER_USERNAME}
      - TEST_USER_PASSWORD=${TEST_USER_PASSWORD}
      - TEST_USER_ROLES=${TEST_USER_ROLES}
      - TEST_USER_NAME=${TEST_USER_NAME}

      - DB_AUTH_SERVICE_PASSWORD=${DB_AUTH_SERVICE_PASSWORD}
      - DB_URL=${DB_URL}
      - DB_POOL_SIZE=${DB_POOL_SIZE}
      - DB_MIN_IDLE=${DB_MIN_IDLE}
      - DB_POOL_NAME=${DB_POOL_NAME}
      - JPA_SHOW_SQL=${JPA_SHOW_SQL}

      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
      args:
        SERVICE_PORT: ${FRONTEND_PORT}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - FRONTEND_PORT=${FRONTEND_PORT}
      - AUTH_SERVER=${AUTH_SERVER}

  file-manager:
    build:
      context: ../file-manager
      dockerfile: Dockerfile
      args:
        SERVICE_PORT: ${FILE_MANAGER_PORT}
    ports:
      - "${FILE_MANAGER_PORT}:${FILE_MANAGER_PORT}"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - FILE_MANAGER_PORT=${FILE_MANAGER_PORT}

      - AUTH_SERVER=${AUTH_SERVER}

      - MINIO_CONTAINER_URL=${MINIO_CONTAINER_URL}
      - MINIO_URL=${MINIO_URL}
      - MINIO_EXTERNAL_URL=${MINIO_EXTERNAL_URL}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}

      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}

      - MONGODB_HOST=${MONGODB_HOST}
      - MONGODB_PORT=${MONGODB_PORT}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_AUTH_SOURCE=${MONGODB_AUTH_SOURCE}
      - MONGODB_AUTO_INDEX=${MONGODB_AUTO_INDEX}

      - KAFKA_BOOTSTRAP_SERVER=${KAFKA_BOOTSTRAP_SERVER}

      - MONITORING_ENABLED=${MONITORING_ENABLED}
      - MONITORING_ACCESS=${MONITORING_ACCESS}
    depends_on:
      mongodb:
        condition: service_healthy
      redpanda:
        condition: service_started
      minio:
        condition: service_started
      redis:
        condition: service_started
    volumes:
      - chunks:/chunks

  media-handler:
    build:
      context: ../media-handler
      dockerfile: Dockerfile
      args:
        SERVICE_PORT: ${MEDIA_HANDLER_PORT}
    ports:
      - "${MEDIA_HANDLER_PORT}:${MEDIA_HANDLER_PORT}"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - MEDIA_UPLOAD_PORT=${MEDIA_UPLOAD_PORT}

      - AUTH_SERVER=${AUTH_SERVER}

      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}

      - MINIO_CONTAINER_URL=${MINIO_CONTAINER_URL}
      - MINIO_EXTERNAL_URL=${MINIO_EXTERNAL_URL}
      - MINIO_URL=${MINIO_URL}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}

      - DB_MEDIA_HANDLER_PASSWORD=${DB_MEDIA_HANDLER_PASSWORD}
      - DB_URL=${DB_URL}
      - DB_POOL_SIZE=${DB_POOL_SIZE}
      - DB_MIN_IDLE=${DB_MIN_IDLE}
      - DB_POOL_NAME=${DB_POOL_NAME}
      - JPA_SHOW_SQL=${JPA_SHOW_SQL}

      - KAFKA_BOOTSTRAP_SERVER=${KAFKA_BOOTSTRAP_SERVER}

      - THUMBNAIL_DISK=${THUMBNAIL_DISK}
    depends_on:
      postgres:
        condition: service_healthy
      redpanda:
        condition: service_started
      redis:
        condition: service_started
      minio:
        condition: service_started
    volumes:
      - chunks:/chunks

  search-service:
    build:
      context: ../search-service
      dockerfile: Dockerfile
      args:
        SERVICE_PORT: ${SEARCH_SERVICE_PORT}
    ports:
      - "${SEARCH_SERVICE_PORT}:${SEARCH_SERVICE_PORT}"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SEARCH_SERVICE_PORT=${SEARCH_SERVICE_PORT}

      - OPENSEARCH_HOST=${OPENSEARCH_HOST}
      - OPENSEARCH_PORT=${OPENSEARCH_PORT}

      - MINIO_CONTAINER_URL=${MINIO_CONTAINER_URL}
      - MINIO_URL=${MINIO_URL}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}

      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}

      - DB_MEDIA_HANDLER_PASSWORD=${DB_MEDIA_HANDLER_PASSWORD}
      - DB_URL=${DB_URL}
      - DB_POOL_SIZE=${DB_POOL_SIZE}
      - DB_MIN_IDLE=${DB_MIN_IDLE}
      - DB_POOL_NAME=${DB_POOL_NAME}
      - JPA_SHOW_SQL=${JPA_SHOW_SQL}

      - KAFKA_BOOTSTRAP_SERVER=${KAFKA_BOOTSTRAP_SERVER}

      - ALWAYS_SHOW_ORIGINAL_RESOLUTION=${ALWAYS_SHOW_ORIGINAL_RESOLUTION}
    depends_on:
      opensearch:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redpanda:
        condition: service_started
      redis:
        condition: service_started
      minio:
        condition: service_started

  workers:
    build:
      context: ../workers
      dockerfile: Dockerfile
      args:
        SERVICE_PORT: ${WORKERS_PORT}
    ports:
      - "${WORKERS_PORT}:${WORKERS_PORT}"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - WORKERS_PORT=${WORKERS_PORT}

      - AUTH_SERVER=${AUTH_SERVER}

      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}

      - MINIO_CONTAINER_URL=${MINIO_CONTAINER_URL}
      - MINIO_URL=${MINIO_URL}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}

      - DB_MEDIA_HANDLER_PASSWORD=${DB_MEDIA_HANDLER_PASSWORD}
      - DB_URL=${DB_URL}
      - DB_POOL_SIZE=${DB_POOL_SIZE}
      - DB_MIN_IDLE=${DB_MIN_IDLE}
      - DB_POOL_NAME=${DB_POOL_NAME}
      - JPA_SHOW_SQL=${JPA_SHOW_SQL}

      - KAFKA_BOOTSTRAP_SERVER=${KAFKA_BOOTSTRAP_SERVER}

      - GRPC_FILE_PROVIDER_ADDRESS=static://file-manager:9090

      - NUMBER_OF_THREADS=${NUMBER_OF_THREADS}
      - WEBSOCKET_ALLOWED_ORIGINS=${WEBSOCKET_ALLOWED_ORIGINS}
    depends_on:
      postgres:
        condition: service_healthy
      redpanda:
        condition: service_started
      minio:
        condition: service_started
      redis:
        condition: service_started
      file-manager:
        condition: service_started
    volumes:
      - chunks:/chunks

  media-backup:
    build:
      context: ../media-backup
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - MINIO_CONTAINER_URL=${MINIO_CONTAINER_URL}
      - MINIO_URL=${MINIO_URL}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}

      - KAFKA_BOOTSTRAP_SERVER=${KAFKA_BOOTSTRAP_SERVER}

      - BACKUP_LOCATION=${BACKUP_LOCATION}
      - BACKUP_ENABLED=${BACKUP_ENABLED}
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_started
      redpanda:
        condition: service_started
    volumes:
      - ${BACKUP_PATH}:${BACKUP_LOCATION}



  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
    container_name: minio
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web console
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
      MINIO_API_STALE_UPLOADS_EXPIRY: 1h
      MINIO_API_STALE_UPLOADS_CLEANUP_INTERVAL: 1h  # check hourly
    volumes:
      - ${MINIO_VOLUME}:/data
    command: server /data --console-address ":9001"

  minio-init:
    image: minio/mc
    container_name: minio-init
    depends_on:
      - minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    volumes:
      - ../.docker/minio/minio-init.sh:/minio-init.sh:ro
    entrypoint: [ "/bin/sh", "/minio-init.sh" ]

  nginx:
    build:
      context: ../.docker/nginx
      dockerfile: Dockerfile
    image: my-nginx/openresty:1.27.1.2-0-bookworm-fat
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - minio
    volumes:
      - ../.docker/nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      - ../.docker/nginx/proxy.conf:/usr/local/openresty/nginx/conf/proxy.conf:ro
      - ../.docker/nginx/streamingservice.conf:/usr/local/openresty/nginx/conf/conf.d/streamingservice.conf:ro
      - chunks:/chunks
    extra_hosts:
      - "host.docker.internal:host-gateway"

  opensearch:
    image: opensearchproject/opensearch:3.3.2
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms${OPENSEARCH_HEAP_GB}g -Xmx${OPENSEARCH_HEAP_GB}g
      - plugins.security.disabled=true
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9600:9600"
    healthcheck:
      # We check if the cluster status is 'green' or 'yellow'
      test: [ "CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -qE 'green|yellow'" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s # Give it 10s to boot before even trying to check
    volumes:
      - ${OPENSEARCH_VOLUME}:/usr/share/opensearch/data

  redis:
    image: redis:7.4.7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command:
      - redis-server
      - --requirepass ${REDIS_PASSWORD}
      - --save ""
      - --appendonly no

  postgres:
    image: postgres:18
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ${POSTGRES_VOLUME}:/var/lib/postgresql

  postgres-init:
    image: postgres:18
    container_name: postgres-init
    depends_on:
      - postgres
    restart: "no"
    entrypoint: [ "/bin/bash", "/scripts/bootstrap.sh" ]
    environment:
      DB_HOST: postgres
      DB_PORT: ${DB_PORT}
      DB_SUPERUSER: ${DB_USERNAME}
      DB_SUPERUSER_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ../.docker/postgres/initdb.d:/scripts

  redpanda:
    image: redpandadata/redpanda:v25.2.12
    container_name: redpanda_kafka
    ports:
      - "9092:9092"       # Kafka API
      - "9644:9644"       # Admin API
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp=1
      - --memory=1G
      - --reserve-memory=0M
      - --node-id=0
      - --check=false
      - --kafka-addr=INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
      - --advertise-kafka-addr=INTERNAL://redpanda:29092,EXTERNAL://localhost:9092
    volumes:
      - ${REDPANDA_VOLUME}:/var/lib/redpanda/data

  mongodb:
    image: mongodb/mongodb-atlas-local:7.0.5
    container_name: mongodb
    hostname: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGODB_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGODB_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_INITDB_DATABASE: ${MONGODB_DATABASE}
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_AUTH_SOURCE: ${MONGODB_AUTH_SOURCE}
    healthcheck:
      test: mongosh --username "$MONGODB_USERNAME" --password "$MONGODB_PASSWORD" --authenticationDatabase "$MONGODB_AUTH_SOURCE" --eval "db.adminCommand('ping')"
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ${MONGODB_VOLUME}:/data/db
      - atlas_config:/data/configdb
    user: "0:0"


  # Metrics Storage (Prometheus)
  prometheus:
    image: prom/prometheus:v3.13.0
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-remote-write-receiver'
    volumes:
      - ../.docker/observability/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090" # grpc already used 9090 port, use 9091 for prometheus instead
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # Logs Storage (Loki)
  loki:
    image: grafana/loki:3.6.13
    container_name: loki
    command: -config.file=/etc/loki/local-config.yml
    volumes:
      - ../.docker/observability/loki.yml:/etc/loki/local-config.yml
    ports:
      - "3100:3100"

  # Traces Storage (Tempo)
  tempo:
    image: grafana/tempo:2.9.4
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yml" ]
    volumes:
      - ../.docker/observability/tempo.yml:/etc/tempo.yml
    ports:
      - "3200:3200" # Tempo HTTP

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.157.0
    container_name: otel-collector
    command: [ "--config=/etc/otelcol-contrib/config.yml" ]
    volumes:
      - ../.docker/observability/otel-collector-config.yml:/etc/otelcol-contrib/config.yml
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP HTTP receiver

  grafana:
    image: grafana/grafana:11.6.16
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ../.docker/observability/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ../.docker/observability/grafana.ini:/etc/grafana/grafana.ini
      - ../.docker/observability/provisioning/alerting:/etc/grafana/provisioning/alerting
      - ../.docker/observability/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ../.docker/observability/dashboards:/etc/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      # SMTP Settings
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=${GF_SMTP_USER}
      - GF_SMTP_PASSWORD=${GF_SMTP_PASSWORD}
      - GF_SMTP_FROM_ADDRESS=${GF_SMTP_USER}
      - GF_SMTP_FROM_NAME=Grafana Alerts


volumes:
  chunks:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=${RAM_SIZE_BYTES}
  atlas_config:
